Algoritmo "aula funções matematicas"

Var
   x,y,z,q,w,r,t : real

   delta : real
   a,b,c: real
   X1 : real
   x2 : real
   
Inicio
 x <- 2.0
 y <- 3.0
 z <- -7.0
 
 A <- 4.0
 B <- 2.0
 C <- 6.0
 
 q <- exp(x,y)
 w <- raizq(Y)
 r <- pi
 t <- abs(z)

 delta <- exp(b,2.0) - 4* a* c
 X1 <- (-b + raizq(delta))/(2.0* a)
 X2 <- (-b - raizq(delta))/(2.0* a)
 
 escreval(q)
 escreval(w)
 escreval(r)
 escreval(t)
 escreval(delta)
 escreval(X1)
 escreval(X2)



Fimalgoritmo