Algoritmo "aula leia"

Var
   idade : inteiro
   salario1,salario2 :real
   nome: caractere



Inicio
   escreva("Digite seu nome: ")
   leia(nome)
   escreva("Digite sua idade: ")
   leia(idade)
   escreval("Digite o quanto vc ganhou nois ultimos dois meses: ")
   leia(salario1)
   leia(salario2)
   
   escreval("DADOS DIGITADOS:")
   escreval("nome =",nome)
   escreval("idade =",idade)
   escreval("salario1 =",salario1:8:2)
   escreval("salario2 =",salario2:8:2)



Fimalgoritmo