Algoritmo "Teste_dia_da_semana_ESCOLHA"

Var
   X: inteiro
   Dia: Caractere
Inicio
   leia(X)
   
   escolha X
   caso 1
      Dia <- "Domingo"
   Caso 2
      Dia <- "Segunda"
   Caso 3
      Dia <- "Terça"
   Caso 4
      Dia <- "Quarta"
   Caso 5
      Dia <- "Quinta"
   caso 6
      Dia <- "Sexta"
   Caso 7
      Dia <- "Sabado"
   outrocaso
      Dia <- "Valor invalido"
   fimescolha
   
   escreval("Dia da semana: ",Dia)


Fimalgoritmo